### ISSUE TITLE
pkg_resources.DistributionNotFound: pyserial

### ISSUE THREAD

**Issue by alancairns** [ntoll/microfs#6] opened 2018-01-25 19:02 UTC
I am using an iMac with macOS High Sierra Version 10.13.2

I have installed uflash and microfs using:
pip install uflash
pip install microfs

flash works fine but I get these errors when - use microfs:
ufs ls
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/ufs", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distribute-0.6.27-py2.7.egg/pkg_resources.py", line 2735, in <module>
    working_set.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distribute-0.6.27-py2.7.egg/pkg_resources.py", line 690, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distribute-0.6.27-py2.7.egg/pkg_resources.py", line 588, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pyserial

I would be grateful for any advice you could provide:

**Comment by ntoll** [comment] 2018-01-25 20:28
Hi @alancairns,

I assume you're using a virtualenv..? If so, can you paste the result of `pip freeze` please..?

Once done, try, `pip install pyserial` and tell me how you get on. I've just checked, and `microfs` tells pip that it needs `pyserial` in order to work. It appears from the error message that this hasn't happened.

Alternatively, do you already have `pyserial` installed. If so, what version. The `microfs` command expects `pyserial` > 3.*.

Hope this helps,

N.

**Comment by alancairns** [comment] 2018-01-25 20:45
Thanks so much for you prompt response.  I’m not using virtualenv, I’m not sure what it is. If I have to use it I’ll go and find out how.

Here’s the output from pip freeze:

beautifulsoup4==4.2.0
gspread==0.0.15
microfs==1.2.2
pep8==1.7.0
pyflakes==1.3.0
pyOSC==0.3.5b5294
pyserial==3.4
scratchpy==0.1.0
uflash==1.0.8

Thank you so much.

Alan

**Comment by alancairns** [comment] 2018-01-26 08:35
Hi Nicholas

Once again I’m grateful for your response.  I’ve installed virtualenv then installed microfs and it is now working. I’am unfamiliar with github but having raised an issue do you want me to update it?

Thanks again

Alan

**Comment by ntoll** [comment] 2018-01-26 08:42
Hi Alan,

No problem and I'm glad to hear it's working. I'll close this issue since the problem isn't with microfs but some sort of packaging oddness (i.e. it's nothing I can fix in the microfs code).

Thanks for taking the time to report it.

N.

**Closed by ntoll** 2018-01-26 08:42 UTC
